# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b29997b99a19a0c2f802482511a6db7005e842303a1c6728042f22473e044719a6275d3900a70d33a290ecfd884d8729a81283b1e719f33de4b68e84db3e1b9b

test:
  secret_key_base: 10c9f1f80b84bb575ce88cb337c39f6e27c87cd3cd7bbbdebe31b853c78cfe428c874ed0375b3cb7cdb065af529d14b1fb4d7a59d07e564429710892b9c344d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
